"" Packages
call plug#begin('~/.vim/plugins')

Plug 'liuchengxu/vim-better-default'
Plug 'chriskempson/base16-vim'
Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'
Plug 'editorconfig/editorconfig-vim'
Plug 'w0rp/ale'
Plug 'mattn/emmet-vim'
Plug 'sheerun/vim-polyglot'

call plug#end()

"" Leader mappings
let mapleader=','
map <leader>ss :source ~/.vimrc<CR>
map <leader>bd :bd<CR>
inoremap jk <esc>

"" Color scheme
let base16colorspace=256
colorscheme base16-tomorrow-night

"" Airline
set laststatus=2
set noshowmode
let g:airline_powerline_fonts=1
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

"" Ale
let g:ale_sign_error="✖"
let g:ale_sign_warning="➤"
highlight clear ALEErrorSign
highlight clear ALEWarningSign

"" Emmet
let g:user_emmet_leader_key='<C-Z>'
let g:user_emmet_install_global=0
autocmd FileType html,css EmmetInstall

